import Head from 'next/head';
import { ClientOnlyColorModeSwitch } from '@app/shared/components/color-mode/ColorMode';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline dark:text-cyan-950 text-green-400">
          Hello world!
        </h1>
        <ClientOnlyColorModeSwitch />
      </main>
    </>
  );
}
